# Generated by Django 4.2.15 on 2024-11-05 14:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_task', models.IntegerField(verbose_name='Count task')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title task list')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Archived', 'Archived'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Created', max_length=20, verbose_name='Task status')),
                ('task_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.schoolclass', verbose_name='Task for')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_to_the_task', models.CharField(verbose_name='Answer to task')),
                ('sequence_number', models.IntegerField(verbose_name='Sequence number')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Title to task')),
                ('description', models.TextField(max_length=300, null=True, verbose_name='Description')),
                ('time_to_task', models.DurationField(blank=True, null=True, verbose_name='Time to task')),
                ('additional_condition', models.CharField(choices=[('None', 'Without additional tasks'), ('Photo', 'Take a picture of the answer')], max_length=255, null=True, verbose_name='Additional condition')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='tasks_media/docx/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='DOCX file')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='tasks_media/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'MPG', 'mkv', 'mov'])], verbose_name='Video file')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_app.tasklist', verbose_name='List tasks')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Answer reviewed')),
                ('execution_time', models.DateTimeField(default=None, null=True, verbose_name='Execution time')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.tasklist', verbose_name='Task list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, null=True, verbose_name='Answer')),
                ('photo_to_the_answer', models.ImageField(null=True, upload_to='tasks_media/images/', verbose_name='Photo to answer')),
                ('answer_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.answerlist', verbose_name='List answers')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.task', verbose_name='Task')),
            ],
        ),
    ]
