# Generated by Django 4.2.15 on 2024-10-06 15:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_task', models.IntegerField(verbose_name='Count task')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title list tasks')),
                ('task_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.schoolclass', verbose_name='Task for')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_to_the_task', models.CharField(verbose_name='Answer to task')),
                ('sequence_number', models.IntegerField(verbose_name='Sequence number')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Title to task')),
                ('description', models.TextField(max_length=300, null=True, verbose_name='Description')),
                ('time_to_task', models.DurationField(blank=True, null=True, verbose_name='Time to task')),
                ('additional_condition', models.CharField(choices=[('None', 'Without additional tasks'), ('Photo', 'Take a picture of the answer')], max_length=255, null=True, verbose_name='Additional condition')),
                ('docx', models.FileField(null=True, upload_to='tasks_media/docx/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='DOCX file')),
                ('video', models.FileField(null=True, upload_to='tasks_media/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'MPG', 'mkv', 'mov'])], verbose_name='Video file')),
                ('list_tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_app.listtasks', verbose_name='List tasks')),
            ],
        ),
        migrations.CreateModel(
            name='ListAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.student', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(null=True, verbose_name='Answer')),
                ('photo_to_the_answer', models.ImageField(null=True, upload_to='tasks_media/images/', verbose_name='Photo to answer')),
                ('list_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.listanswer', verbose_name='List answer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.task', verbose_name='Task')),
            ],
        ),
    ]
